AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs Service Reports
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: Python 3.6
      CodeUri: .
      Description: Resources report 
      MemorySize: 1536
      Timeout: 10
      Role: 'arn:aws:iam::707765467002:role/LambdaReports'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /LambdaReports
            Method: ANY