AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs Service Reports
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: Python 3.6
      CodeUri: .
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /LambdaReports
            Method: GET